name: Terraform CI
on: [push]
jobs:
  tflint:
    name: tflint runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init tflint
        run: tflint --init

      - name: Run tflint
        run: tflint -f compact
