name: Terraform CI
run-name: "CI: ${{ github.event.head_commit.message }}"
on:
  push:
  pull_request:
jobs:
  tfsec:
    name: tfsec with reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: reviewdog/actions-tfsec@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: src
          fail_on_error: true

  tflint:
    name: tflint runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init tflint
        run: tflint --init
        working-directory: ./src/

      - name: Run tflint
        run: tflint -f compact
        working-directory: ./src/
